#if os(macOS)
  import SwiftParser
  import SwiftSyntax

  /// Generates the NativeActivity bridge in the app's own file so private app
  /// types and targets with an explicit sources list keep working.
  enum EditorAndroidAppBootstrap {
    static func prepare(_ sources: [String]) throws -> [String] {
      let trees = sources.map { Parser.parse(source: $0) }
      let detector = AndroidAppEntryDetector(viewMode: .sourceAccurate)
      for (index, tree) in trees.enumerated() {
        guard !tree.hasError else {
          throw EditorPreviewBuildFailure(message: "Cannot generate Android startup from invalid Swift sources.")
        }
        detector.sourceIndex = index
        detector.walk(tree)
      }
      guard detector.androidEntries <= 1 else {
        throw EditorPreviewBuildFailure(message: "Android export requires exactly one ada_android_start entry point.")
      }
      if detector.androidEntries == 1 { return sources }
      guard detector.mainTypes.count == 1, let entry = detector.mainTypes.first,
        entry.isApp, !entry.isGeneric, !entry.isNested
      else {
        throw EditorPreviewBuildFailure(
          message: "Android export requires one top-level, nongeneric @main AdaEngine App or an ada_android_start entry point.")
      }

      var result = sources
      let rewriter = AndroidAppMainRewriter(mainAttribute: entry.mainAttribute)
      result[entry.sourceIndex] = rewriter.rewrite(trees[entry.sourceIndex]).description + """


        // Generated by Ada Studio for Android NativeActivity.
        import AdaEngine

        @_cdecl("ada_android_start")
        public func adaStudioAndroidStart() {
            AdaEngine.AndroidRuntime.start { \(entry.name)() }
        }

        """
      return result
    }
  }

  private final class AndroidAppEntryDetector: SyntaxVisitor {
    struct Entry {
      var sourceIndex: Int
      var name: String
      var mainAttribute: SyntaxIdentifier
      var isApp: Bool
      var isGeneric: Bool
      var isNested: Bool
    }

    var sourceIndex = 0
    var mainTypes: [Entry] = []
    var androidEntries = 0

    override func visit(_ node: StructDeclSyntax) -> SyntaxVisitorContinueKind {
      collect(node, name: node.name, attributes: node.attributes,
        inheritance: node.inheritanceClause, isGeneric: node.genericParameterClause != nil)
      return .visitChildren
    }

    override func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind {
      collect(node, name: node.name, attributes: node.attributes,
        inheritance: node.inheritanceClause, isGeneric: node.genericParameterClause != nil)
      return .visitChildren
    }

    override func visit(_ node: EnumDeclSyntax) -> SyntaxVisitorContinueKind {
      collect(node, name: node.name, attributes: node.attributes,
        inheritance: node.inheritanceClause, isGeneric: node.genericParameterClause != nil)
      return .visitChildren
    }

    override func visit(_ node: FunctionDeclSyntax) -> SyntaxVisitorContinueKind {
      for attribute in node.attributes.compactMap({ $0.as(AttributeSyntax.self) }) {
        guard attribute.attributeName.trimmedDescription == "_cdecl",
          case .argumentList(let arguments) = attribute.arguments,
          let literal = arguments.first?.expression.as(StringLiteralExprSyntax.self),
          literal.segments.count == 1,
          literal.segments.first?.as(StringSegmentSyntax.self)?.content.text == "ada_android_start"
        else { continue }
        androidEntries += 1
      }
      return .visitChildren
    }

    private func collect(
      _ node: some SyntaxProtocol, name: TokenSyntax, attributes: AttributeListSyntax,
      inheritance: InheritanceClauseSyntax?, isGeneric: Bool
    ) {
      guard let main = attributes.compactMap({ $0.as(AttributeSyntax.self) }).first(where: {
        $0.attributeName.trimmedDescription == "main"
      }) else { return }
      let isApp = inheritance?.inheritedTypes.contains {
        ["App", "AdaEngine.App"].contains($0.type.trimmedDescription)
      } == true
      var parent = node.parent
      var isNested = false
      while let ancestor = parent {
        if ancestor.is(MemberBlockSyntax.self) { isNested = true }
        parent = ancestor.parent
      }
      mainTypes.append(Entry(
        sourceIndex: sourceIndex, name: name.trimmedDescription, mainAttribute: main.id,
        isApp: isApp, isGeneric: isGeneric, isNested: isNested))
    }
  }

  private final class AndroidAppMainRewriter: SyntaxRewriter {
    let mainAttribute: SyntaxIdentifier

    init(mainAttribute: SyntaxIdentifier) {
      self.mainAttribute = mainAttribute
      super.init(viewMode: .sourceAccurate)
    }

    override func visit(_ node: StructDeclSyntax) -> DeclSyntax {
      var result = super.visit(node)
      result.leadingTrivia = node.leadingTrivia
      return result
    }

    override func visit(_ node: ClassDeclSyntax) -> DeclSyntax {
      var result = super.visit(node)
      result.leadingTrivia = node.leadingTrivia
      return result
    }

    override func visit(_ node: EnumDeclSyntax) -> DeclSyntax {
      var result = super.visit(node)
      result.leadingTrivia = node.leadingTrivia
      return result
    }

    override func visit(_ node: AttributeListSyntax) -> AttributeListSyntax {
      node.filter { $0.as(AttributeSyntax.self)?.id != mainAttribute }
    }
  }
#endif
