//
//  System.swift
//  AdaEngine
//
//  Created by v.prusakov on 5/6/22.
//

import AdaUtils

/// Contains information about current world update.
public struct WorldUpdateContext: Sendable {
    /// The updating world.
    public let world: World

    /// The scheduler that will be used to schedule tasks.
    public let scheduler: SchedulerName
}

/// An object that affects multiple entities in every frame.
///
/// System is a fundomental part of ECS paradigm.
/// Use systems to implement any behavior or logic that updates entities every frame,
/// such as different types of objects or characters. For example, a physics simulation system calculates and applies the affect of gravity, forces, and collisions for all entities.
///
/// A complex game or experience may consist of many systems which need to be executed in a specific order.
/// The dependencies property defines when the update method for each system is called each frame. Update order is defined between system types and not between individual system instances.
///
/// Like example, let's create a movement system:
///
/// ```swift
/// @PlainSystem
/// struct MovementSystem {
///
///     // Configure the query to world.
///     // We want to recieve entities with `PlayerComponent` and `Transform`
///     @FilterQuery<Ref<Transform>, With<PlayerComponent>>
///     private var query
///
///     @Res<Input>
///     private var input
///
///     init(world: World) {}
///
///     func update(context: UpdateContext) {
///         self.query.forEach { transform in
///             if input.isKeyPressed(.space) {
///                 // Add 5 points for vertical direction
///                 // if space button pressed
///                 transform.position.y += 5
///             }
///         }
///     }
/// }
///
/// ```
public protocol System: Sendable {
    typealias UpdateContext = WorldUpdateContext

    /// Creates a new system.
    @preconcurrency init(world: World)

    /// Updates entities every frame.
    @concurrent
    func update(context: UpdateContext) async

    /// An array of queries for this system.
    /// That needs to be updated queries results for this system.
    /// You can ignore this property if you don't use ``EntityQuery`` property wrapper or similar query property wrappers.
    /// - Note: This property is generated by the ``System(dependencies:)`` or
    ///   ``PlainSystem(dependencies:)`` macro from properties whose wrappers conform to
    ///   ``SystemParameter``, such as `@CustomQuery`.
    var queries: SystemQueries { get }

    /// Stable identity used by the scheduler graph.
    /// Instances of the same Swift system type may override this value.
    var systemIdentifier: String { get }

    /// An array of dependencies for this system.
    static var dependencies: [SystemDependency] { get }

    /// The dependencies resolved for this system instance.
    ///
    /// Dynamic systems can override this property when their ordering is not
    /// known at the Swift type level. The default uses ``dependencies``.
    var systemDependencies: [SystemDependency] { get }
}

extension System {
    public static var dependencies: [SystemDependency] {
        return []
    }

    public var systemDependencies: [SystemDependency] {
        Self.dependencies
    }

    public var queries: SystemQueries {
        return SystemQueries(queries: [])
    }

    public var systemIdentifier: String {
        String(reflecting: Self.self)
    }
}

/// A collection of queries for a system.
public struct SystemQueries: Sendable, Equatable {
    public let queries: [any SystemParameter]

    /// Combined world access required by all system parameters.
    public var access: SystemAccessSet {
        var access = SystemAccessSet()
        for query in queries {
            access.formUnion(query.access)
        }
        return access
    }

    /// Initialize a new system queries.
    /// - Parameter queries: The queries to update.
    public init(queries: consuming [any SystemParameter]) {
        self.queries = queries
    }

    /// Update the queries from the world.
    /// - Parameter world: The world to update the queries from.
    public func update(from world: World) {
        let world = world
        for query in queries {
            query.update(from: world)
        }
    }

    @WorldActor
    public func finish(_ world: World) {
        for query in queries {
            query.finish(world)
        }
    }

    public static func == (lhs: Self, rhs: Self) -> Bool {
        for lhsItem in lhs.queries {
            let lhsItemType = type(of: lhsItem)
            if !rhs.queries.contains(where: {
                type(of: $0) == lhsItemType
            }) {
                return false
            }
        }

        return true
    }
}
