/* Generated by Gravity AOT; standalone ABI 3. */
#include <shared/gravity_aot_runtime.h>
static const gravity_aot_class ga_ada_native_async_types[4];
static gravity_aot_value ada_native_async_fn_8(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_9(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_10(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_13(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_14(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_19(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_20(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_21(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_22(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_23(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_24(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_25(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_26(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_27(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_28(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_29(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_fn_30(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_async_field_7(gravity_aot_context *ctx,gravity_aot_value v0) {
(void)v0;
gravity_aot_value result=gravity_aot_null();
gravity_aot_value t2 = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value a4[1]; (void)a4;
gravity_aot_value t3=gravity_aot_call(ctx,t2,"\160\162\157\155\151\163\145",a4,0);
if (ctx->error) goto ga_exit;
gravity_aot_value t1=t3;
(void)t1;
result=t1; goto ga_exit;
ga_exit: return ctx->error?gravity_aot_null():result;
}
static void ada_native_async_resume_8(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
task->values[6] = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)task->values[6];
 (void)(&task->values[12]);
task->values[7]=gravity_aot_call(ctx,task->values[6],"\156\145\170\164\106\162\141\155\145",(&task->values[12]),0);
if (ctx->error) goto ga_exit;
task->values[5]=task->values[7];
(void)task->values[5];
task->waiting=task->values[5]; task->pc=1;
ga_resume_1:;
task->values[4]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[4])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[4];
task->values[10] = task->values[1];
(void)task->values[10];
task->values[11] = gravity_aot_int((int64_t)UINT64_C(2));
(void)task->values[11];
task->values[9] = gravity_aot_binary(ctx, 0, task->values[10], task->values[11]);
if (ctx->error) goto ga_exit;
(void)task->values[9];
result = task->values[9]; goto ga_exit;
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_8(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_8,13,9);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[1]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
task->values[1]=gravity_aot_copy(ctx,args[0]);
return ctx->error?gravity_aot_null():value;
}
static void ada_native_async_resume_9(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
case 2: goto ga_resume_2;
case 3: goto ga_resume_3;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
 (void)(&task->values[37]);
task->values[6] = gravity_aot_int((int64_t)UINT64_C(1));
(void)task->values[6];
(&task->values[37])[0]=gravity_aot_copy(ctx,task->values[6]);
if (ctx->error) goto ga_exit;
task->values[7] = gravity_aot_int((int64_t)UINT64_C(2));
(void)task->values[7];
(&task->values[37])[1]=gravity_aot_copy(ctx,task->values[7]);
if (ctx->error) goto ga_exit;
task->values[8] = gravity_aot_int((int64_t)UINT64_C(3));
(void)task->values[8];
(&task->values[37])[2]=gravity_aot_copy(ctx,task->values[8]);
if (ctx->error) goto ga_exit;
task->values[5] = gravity_aot_list_new(ctx,(&task->values[37]),3);
if (ctx->error) goto ga_exit;
(void)task->values[5];
{ task->cursors[5]=0; task->values[1]=gravity_aot_null(); (void)task->values[1];
while (1) {
if (!gravity_aot_tick(ctx)) goto ga_exit;
int next5=gravity_aot_next(ctx,task->values[5],&task->cursors[5],&task->values[1]);
if (ctx->error) goto ga_exit;
if (!next5) break;
task->values[1]=gravity_aot_copy(ctx,task->values[1]);
if (ctx->error) goto ga_exit;
{
task->values[12] = gravity_aot_field_get(ctx,task->values[0],2);
if (ctx->error) goto ga_exit;
(void)task->values[12];
task->values[15] = task->values[0];
(void)task->values[15];
 (void)(&task->values[40]);
task->values[18] = task->values[1];
(void)task->values[18];
(&task->values[40])[0]=gravity_aot_copy(ctx,task->values[18]);
if (ctx->error) goto ga_exit;
task->values[16]=gravity_aot_call(ctx,task->values[15],"\143\150\151\154\144",(&task->values[40]),1);
if (ctx->error) goto ga_exit;
task->values[14]=task->values[16];
(void)task->values[14];
task->waiting=task->values[14]; task->pc=1;
ga_resume_1:;
task->values[13]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[13])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[13];
task->values[11] = gravity_aot_binary(ctx, 0, task->values[12], task->values[13]);
if (ctx->error) goto ga_exit;
(void)task->values[11];
(void)gravity_aot_field_set(ctx,task->values[0],2,task->values[11]);
if (ctx->error) goto ga_exit;
task->values[10] = task->values[11];
(void)task->values[10];
}
} }
task->values[21] = gravity_aot_get(ctx,gravity_aot_null(),"\124\151\155\145");
if (ctx->error) goto ga_exit;
(void)task->values[21];
 (void)(&task->values[41]);
task->values[24] = gravity_aot_float(0x1.999999999999ap-3);
(void)task->values[24];
(&task->values[41])[0]=gravity_aot_copy(ctx,task->values[24]);
if (ctx->error) goto ga_exit;
task->values[22]=gravity_aot_call(ctx,task->values[21],"\163\154\145\145\160",(&task->values[41]),1);
if (ctx->error) goto ga_exit;
task->values[20]=task->values[22];
(void)task->values[20];
task->waiting=task->values[20]; task->pc=2;
ga_resume_2:;
task->values[19]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[19])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[19];
task->values[26] = gravity_aot_field_get(ctx,task->values[0],3);
if (ctx->error) goto ga_exit;
(void)task->values[26];
task->waiting=task->values[26]; task->pc=3;
ga_resume_3:;
task->values[25]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[25])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[25];
task->values[2] = gravity_aot_copy(ctx,task->values[25]); (void)task->values[2];
if (ctx->error) goto ga_exit;
task->values[29] = gravity_aot_field_get(ctx,task->values[0],2);
if (ctx->error) goto ga_exit;
(void)task->values[29];
task->values[30] = task->values[2];
(void)task->values[30];
task->values[28] = gravity_aot_binary(ctx, 0, task->values[29], task->values[30]);
if (ctx->error) goto ga_exit;
(void)task->values[28];
task->values[32] = gravity_aot_field_get(ctx,task->values[0],0);
if (ctx->error) goto ga_exit;
(void)task->values[32];
(void)gravity_aot_set(ctx,task->values[32],"\162\145\163\165\154\164",task->values[28]);
if (ctx->error) goto ga_exit;
task->values[27] = task->values[28];
(void)task->values[27];
task->values[34] = gravity_aot_bool(1);
(void)task->values[34];
task->values[36] = gravity_aot_field_get(ctx,task->values[0],0);
if (ctx->error) goto ga_exit;
(void)task->values[36];
(void)gravity_aot_set(ctx,task->values[36],"\144\157\156\145",task->values[34]);
if (ctx->error) goto ga_exit;
task->values[33] = task->values[34];
(void)task->values[33];
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_9(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_9,42,33);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[1]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
return ctx->error?gravity_aot_null():value;
}
static gravity_aot_value ada_native_async_fn_10(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[1]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t2 = gravity_aot_field_get(ctx,v0,1);
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value t1 = gravity_aot_unary(ctx, 14, t2);
if (ctx->error) goto ga_exit;
(void)t1;
if (gravity_aot_truth(ctx, t1)) {
{
gravity_aot_value t4 = gravity_aot_bool(1);
(void)t4;
(void)gravity_aot_field_set(ctx,v0,1,t4);
if (ctx->error) goto ga_exit;
gravity_aot_value t3 = t4;
(void)t3;
gravity_aot_value t6 = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)t6;
gravity_aot_value a8[1]; (void)a8;
gravity_aot_value t10 = v0;
(void)t10;
gravity_aot_value a12[1]; (void)a12;
gravity_aot_value t11=gravity_aot_call(ctx,t10,"\141\144\166\141\156\143\145",a12,0);
if (ctx->error) goto ga_exit;
gravity_aot_value t9=t11;
(void)t9;
a8[0]=gravity_aot_copy(ctx,t9);
if (ctx->error) goto ga_exit;
gravity_aot_value t7=gravity_aot_call(ctx,t6,"\163\164\141\162\164",a8,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t5=t7;
(void)t5;
}
}
if (ctx->error) goto ga_exit;
gravity_aot_value t15 = v1;
(void)t15;
gravity_aot_value t16=gravity_aot_get(ctx,t15,"\144\145\154\164\141\124\151\155\145");
if (ctx->error) goto ga_exit;
gravity_aot_value t14=t16;
(void)t14;
gravity_aot_value t17 = gravity_aot_float(0x0p+0);
(void)t17;
gravity_aot_value t13 = gravity_aot_binary(ctx, 7, t14, t17);
if (ctx->error) goto ga_exit;
(void)t13;
if (gravity_aot_truth(ctx, t13)) {
{
gravity_aot_value t19 = gravity_aot_field_get(ctx,v0,3);
if (ctx->error) goto ga_exit;
(void)t19;
gravity_aot_value a21[1]; (void)a21;
gravity_aot_value t22 = gravity_aot_int((int64_t)UINT64_C(30));
(void)t22;
a21[0]=gravity_aot_copy(ctx,t22);
if (ctx->error) goto ga_exit;
gravity_aot_value t20=gravity_aot_call(ctx,t19,"\143\157\155\160\154\145\164\145",a21,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t18=t20;
(void)t18;
}
}
if (ctx->error) goto ga_exit;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_async_fn_13(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[2]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t2 = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value a4[1]; (void)a4;
gravity_aot_value t6 = v0;
(void)t6;
gravity_aot_value a8[1]; (void)a8;
gravity_aot_value t7=gravity_aot_call(ctx,t6,"\141\144\166\141\156\143\145",a8,0);
if (ctx->error) goto ga_exit;
gravity_aot_value t5=t7;
(void)t5;
a4[0]=gravity_aot_copy(ctx,t5);
if (ctx->error) goto ga_exit;
gravity_aot_value t3=gravity_aot_call(ctx,t2,"\163\164\141\162\164",a4,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t1=t3;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static void ada_native_async_resume_14(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
while (1) {
if (!gravity_aot_tick(ctx)) goto ga_exit;
task->values[4] = gravity_aot_field_get(ctx,task->values[0],0);
if (ctx->error) goto ga_exit;
(void)task->values[4];
task->values[5] = gravity_aot_int((int64_t)UINT64_C(10));
(void)task->values[5];
task->values[3] = gravity_aot_binary(ctx, 5, task->values[4], task->values[5]);
if (ctx->error) goto ga_exit;
(void)task->values[3];
if (!gravity_aot_truth(ctx, task->values[3])) break;
if (ctx->error) goto ga_exit;
{
task->values[8] = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)task->values[8];
 (void)(&task->values[15]);
task->values[9]=gravity_aot_call(ctx,task->values[8],"\156\145\170\164\106\162\141\155\145",(&task->values[15]),0);
if (ctx->error) goto ga_exit;
task->values[7]=task->values[9];
(void)task->values[7];
task->waiting=task->values[7]; task->pc=1;
ga_resume_1:;
task->values[6]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[6])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[6];
task->values[13] = gravity_aot_field_get(ctx,task->values[0],0);
if (ctx->error) goto ga_exit;
(void)task->values[13];
task->values[14] = gravity_aot_int((int64_t)UINT64_C(1));
(void)task->values[14];
task->values[12] = gravity_aot_binary(ctx, 0, task->values[13], task->values[14]);
if (ctx->error) goto ga_exit;
(void)task->values[12];
(void)gravity_aot_field_set(ctx,task->values[0],0,task->values[12]);
if (ctx->error) goto ga_exit;
task->values[11] = task->values[12];
(void)task->values[11];
}
}
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_14(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_14,16,13);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[2]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
return ctx->error?gravity_aot_null():value;
}
static gravity_aot_value ada_native_async_fn_19(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t2 = v1;
(void)t2;
(void)gravity_aot_field_set(ctx,v0,2,t2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1 = t2;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_async_fn_20(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
{
gravity_aot_value t2 = gravity_aot_field_get(ctx,v0,2);
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value t3 = gravity_aot_int((int64_t)UINT64_C(0));
(void)t3;
gravity_aot_value t4=gravity_aot_index_get(ctx,t2,t3);
if (ctx->error) goto ga_exit;
gravity_aot_value a6[1]; (void)a6;
gravity_aot_value t5=gravity_aot_call(ctx,t4,"\151\163\103\157\155\160\154\145\164\145",a6,0);
if (ctx->error) goto ga_exit;
gravity_aot_value t1=t5;
(void)t1;
result = t1; goto ga_exit;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_async_fn_21(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
{
gravity_aot_value t2 = gravity_aot_null();
(void)t2;
(void)gravity_aot_field_set(ctx,v0,2,t2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1 = t2;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_async_fn_22(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
{
gravity_aot_value t2 = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value a4[1]; (void)a4;
gravity_aot_value t6 = v0;
(void)t6;
gravity_aot_value a8[1]; (void)a8;
gravity_aot_value t7=gravity_aot_call(ctx,t6,"\157\162\144\145\162\145\144",a8,0);
if (ctx->error) goto ga_exit;
gravity_aot_value t5=t7;
(void)t5;
a4[0]=gravity_aot_copy(ctx,t5);
if (ctx->error) goto ga_exit;
gravity_aot_value t3=gravity_aot_call(ctx,t2,"\163\164\141\162\164",a4,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t1=t3;
(void)t1;
gravity_aot_value t10 = gravity_aot_int((int64_t)UINT64_C(7));
(void)t10;
(void)gravity_aot_field_set(ctx,v0,1,t10);
if (ctx->error) goto ga_exit;
gravity_aot_value t9 = t10;
(void)t9;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static void ada_native_async_resume_23(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
task->values[4] = gravity_aot_field_get(ctx,task->values[0],1);
if (ctx->error) goto ga_exit;
(void)task->values[4];
(void)gravity_aot_field_set(ctx,task->values[0],0,task->values[4]);
if (ctx->error) goto ga_exit;
task->values[3] = task->values[4];
(void)task->values[3];
task->values[7] = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)task->values[7];
 (void)(&task->values[14]);
task->values[8]=gravity_aot_call(ctx,task->values[7],"\156\145\170\164\106\162\141\155\145",(&task->values[14]),0);
if (ctx->error) goto ga_exit;
task->values[6]=task->values[8];
(void)task->values[6];
task->waiting=task->values[6]; task->pc=1;
ga_resume_1:;
task->values[5]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[5])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[5];
task->values[12] = gravity_aot_field_get(ctx,task->values[0],0);
if (ctx->error) goto ga_exit;
(void)task->values[12];
task->values[13] = gravity_aot_int((int64_t)UINT64_C(1));
(void)task->values[13];
task->values[11] = gravity_aot_binary(ctx, 0, task->values[12], task->values[13]);
if (ctx->error) goto ga_exit;
(void)task->values[11];
(void)gravity_aot_field_set(ctx,task->values[0],0,task->values[11]);
if (ctx->error) goto ga_exit;
task->values[10] = task->values[11];
(void)task->values[10];
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_23(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_23,15,12);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
return ctx->error?gravity_aot_null():value;
}
static void ada_native_async_resume_24(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
task->values[6] = gravity_aot_field_get(ctx,task->values[0],0);
if (ctx->error) goto ga_exit;
(void)task->values[6];
task->values[7] = gravity_aot_int((int64_t)UINT64_C(1));
(void)task->values[7];
task->values[5] = gravity_aot_binary(ctx, 0, task->values[6], task->values[7]);
if (ctx->error) goto ga_exit;
(void)task->values[5];
(void)gravity_aot_field_set(ctx,task->values[0],0,task->values[5]);
if (ctx->error) goto ga_exit;
task->values[4] = task->values[5];
(void)task->values[4];
task->values[10] = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)task->values[10];
 (void)(&task->values[16]);
task->values[11]=gravity_aot_call(ctx,task->values[10],"\156\145\170\164\106\162\141\155\145",(&task->values[16]),0);
if (ctx->error) goto ga_exit;
task->values[9]=task->values[11];
(void)task->values[9];
task->waiting=task->values[9]; task->pc=1;
ga_resume_1:;
task->values[8]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[8])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[8];
task->values[14] = task->values[1];
(void)task->values[14];
task->values[15]=gravity_aot_get(ctx,task->values[14],"\144\145\154\164\141\124\151\155\145");
if (ctx->error) goto ga_exit;
task->values[13]=task->values[15];
(void)task->values[13];
result = task->values[13]; goto ga_exit;
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_24(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_24,17,13);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
task->values[1]=gravity_aot_copy(ctx,args[0]);
return ctx->error?gravity_aot_null():value;
}
static void ada_native_async_resume_25(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
 (void)(&task->values[19]);
task->values[5] = gravity_aot_int((int64_t)UINT64_C(1));
(void)task->values[5];
(&task->values[19])[0]=gravity_aot_copy(ctx,task->values[5]);
if (ctx->error) goto ga_exit;
task->values[6] = gravity_aot_int((int64_t)UINT64_C(2));
(void)task->values[6];
(&task->values[19])[1]=gravity_aot_copy(ctx,task->values[6]);
if (ctx->error) goto ga_exit;
task->values[7] = gravity_aot_int((int64_t)UINT64_C(3));
(void)task->values[7];
(&task->values[19])[2]=gravity_aot_copy(ctx,task->values[7]);
if (ctx->error) goto ga_exit;
task->values[4] = gravity_aot_list_new(ctx,(&task->values[19]),3);
if (ctx->error) goto ga_exit;
(void)task->values[4];
{ task->cursors[5]=0; task->values[1]=gravity_aot_null(); (void)task->values[1];
while (1) {
if (!gravity_aot_tick(ctx)) goto ga_exit;
int next5=gravity_aot_next(ctx,task->values[4],&task->cursors[5],&task->values[1]);
if (ctx->error) goto ga_exit;
if (!next5) break;
task->values[1]=gravity_aot_copy(ctx,task->values[1]);
if (ctx->error) goto ga_exit;
{
task->values[11] = gravity_aot_field_get(ctx,task->values[0],0);
if (ctx->error) goto ga_exit;
(void)task->values[11];
task->values[14] = task->values[0];
(void)task->values[14];
 (void)(&task->values[22]);
task->values[17] = task->values[1];
(void)task->values[17];
(&task->values[22])[0]=gravity_aot_copy(ctx,task->values[17]);
if (ctx->error) goto ga_exit;
task->values[15]=gravity_aot_call(ctx,task->values[14],"\143\150\151\154\144",(&task->values[22]),1);
if (ctx->error) goto ga_exit;
task->values[13]=task->values[15];
(void)task->values[13];
task->waiting=task->values[13]; task->pc=1;
ga_resume_1:;
task->values[12]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[12])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[12];
task->values[10] = gravity_aot_binary(ctx, 0, task->values[11], task->values[12]);
if (ctx->error) goto ga_exit;
(void)task->values[10];
(void)gravity_aot_field_set(ctx,task->values[0],0,task->values[10]);
if (ctx->error) goto ga_exit;
task->values[9] = task->values[10];
(void)task->values[9];
}
} }
task->values[18] = gravity_aot_field_get(ctx,task->values[0],0);
if (ctx->error) goto ga_exit;
(void)task->values[18];
result = task->values[18]; goto ga_exit;
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_25(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_25,23,16);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
return ctx->error?gravity_aot_null():value;
}
static void ada_native_async_resume_26(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
task->values[6] = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)task->values[6];
 (void)(&task->values[12]);
task->values[7]=gravity_aot_call(ctx,task->values[6],"\156\145\170\164\106\162\141\155\145",(&task->values[12]),0);
if (ctx->error) goto ga_exit;
task->values[5]=task->values[7];
(void)task->values[5];
task->waiting=task->values[5]; task->pc=1;
ga_resume_1:;
task->values[4]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[4])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[4];
task->values[10] = task->values[1];
(void)task->values[10];
task->values[11] = gravity_aot_int((int64_t)UINT64_C(2));
(void)task->values[11];
task->values[9] = gravity_aot_binary(ctx, 0, task->values[10], task->values[11]);
if (ctx->error) goto ga_exit;
(void)task->values[9];
result = task->values[9]; goto ga_exit;
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_26(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_26,13,9);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
task->values[1]=gravity_aot_copy(ctx,args[0]);
return ctx->error?gravity_aot_null():value;
}
static void ada_native_async_resume_27(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
task->values[4] = gravity_aot_int((int64_t)UINT64_C(0));
(void)task->values[4];
task->values[1] = gravity_aot_copy(ctx,task->values[4]); (void)task->values[1];
if (ctx->error) goto ga_exit;
while (1) {
if (!gravity_aot_tick(ctx)) goto ga_exit;
task->values[6] = task->values[1];
(void)task->values[6];
task->values[7] = gravity_aot_int((int64_t)UINT64_C(5000));
(void)task->values[7];
task->values[5] = gravity_aot_binary(ctx, 5, task->values[6], task->values[7]);
if (ctx->error) goto ga_exit;
(void)task->values[5];
if (!gravity_aot_truth(ctx, task->values[5])) break;
if (ctx->error) goto ga_exit;
{
task->values[10] = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)task->values[10];
 (void)(&task->values[18]);
task->values[11]=gravity_aot_call(ctx,task->values[10],"\156\145\170\164\106\162\141\155\145",(&task->values[18]),0);
if (ctx->error) goto ga_exit;
task->values[9]=task->values[11];
(void)task->values[9];
task->waiting=task->values[9]; task->pc=1;
ga_resume_1:;
task->values[8]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[8])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[8];
task->values[15] = task->values[1];
(void)task->values[15];
task->values[16] = gravity_aot_int((int64_t)UINT64_C(1));
(void)task->values[16];
task->values[14] = gravity_aot_binary(ctx, 0, task->values[15], task->values[16]);
if (ctx->error) goto ga_exit;
(void)task->values[14];
task->values[1]=gravity_aot_copy(ctx,task->values[14]);
if (ctx->error) goto ga_exit;
task->values[13] = task->values[14];
(void)task->values[13];
}
}
task->values[17] = task->values[1];
(void)task->values[17];
result = task->values[17]; goto ga_exit;
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_27(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_27,19,15);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
return ctx->error?gravity_aot_null():value;
}
static void ada_native_async_resume_28(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
task->values[3] = gravity_aot_int((int64_t)UINT64_C(9));
(void)task->values[3];
result = task->values[3]; goto ga_exit;
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
}
static gravity_aot_value ada_native_async_fn_28(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_28,4,2);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
return ctx->error?gravity_aot_null():value;
}
static void ada_native_async_resume_29(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
while (1) {
if (!gravity_aot_tick(ctx)) goto ga_exit;
task->values[3] = gravity_aot_bool(1);
(void)task->values[3];
if (!gravity_aot_truth(ctx, task->values[3])) break;
if (ctx->error) goto ga_exit;
{
}
}
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
}
static gravity_aot_value ada_native_async_fn_29(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=0 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_29,4,2);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
return ctx->error?gravity_aot_null():value;
}
static void ada_native_async_resume_30(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
 (void)(&task->values[20]);
task->values[9] = gravity_aot_get(ctx,gravity_aot_null(),"\137\137\141\144\141\101\163\163\145\164\163");
if (ctx->error) goto ga_exit;
(void)task->values[9];
 (void)(&task->values[21]);
 (void)(&task->values[22]);
task->values[13] = gravity_aot_string("\154\157\141\144\101\163\171\156\143", 9);
(void)task->values[13];
(&task->values[22])[0]=gravity_aot_copy(ctx,task->values[13]);
if (ctx->error) goto ga_exit;
task->values[14] = task->values[1];
(void)task->values[14];
(&task->values[22])[1]=gravity_aot_copy(ctx,task->values[14]);
if (ctx->error) goto ga_exit;
task->values[12] = gravity_aot_list_new(ctx,(&task->values[22]),2);
if (ctx->error) goto ga_exit;
(void)task->values[12];
(&task->values[21])[0]=gravity_aot_copy(ctx,task->values[12]);
if (ctx->error) goto ga_exit;
task->values[10]=gravity_aot_call(ctx,task->values[9],"\142\145\147\151\156",(&task->values[21]),1);
if (ctx->error) goto ga_exit;
task->values[8]=task->values[10];
(void)task->values[8];
(&task->values[20])[0]=gravity_aot_copy(ctx,task->values[8]);
if (ctx->error) goto ga_exit;
task->values[15]=gravity_aot_call(ctx,gravity_aot_null(),"\137\137\141\144\141\124\141\163\153\106\162\157\155\117\160\145\162\141\164\151\157\156",(&task->values[20]),1);
if (ctx->error) goto ga_exit;
task->values[6]=task->values[15];
(void)task->values[6];
task->waiting=task->values[6]; task->pc=1;
ga_resume_1:;
task->values[5]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[5])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[5];
task->values[2] = gravity_aot_copy(ctx,task->values[5]); (void)task->values[2];
if (ctx->error) goto ga_exit;
task->values[17] = task->values[2];
(void)task->values[17];
 (void)(&task->values[24]);
task->values[18]=gravity_aot_call(ctx,task->values[17],"\166\141\154\165\145",(&task->values[24]),0);
if (ctx->error) goto ga_exit;
task->values[16]=task->values[18];
(void)task->values[16];
result = task->values[16]; goto ga_exit;
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_async_fn_30(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_async_resume_30,25,16);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_async_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
task->values[1]=gravity_aot_copy(ctx,args[0]);
return ctx->error?gravity_aot_null():value;
}
static const gravity_aot_attribute_value ga_attr_value_1 = {.kind=1,.count=0,.text="\141\157\164\056\141\163\171\156\143\056\163\164\141\164\163"};
static const gravity_aot_attribute_value ga_attr_value_2 = {.kind=4,.count=0,.integer=1};
static const gravity_aot_attribute_argument ga_args_0_0[] = {
{"\151\144",&ga_attr_value_1},
{"\141\165\164\157\111\156\163\145\162\164",&ga_attr_value_2},
};
static const gravity_aot_attribute ga_attrs_0[] = {
{"\162\145\163\157\165\162\143\145",2,0,5,1,ga_args_0_0},
};
static const gravity_aot_attribute ga_attrs_1[] = {
{"\145\170\160\157\162\164",0,0,6,27,NULL},
};
static const gravity_aot_attribute ga_attrs_2[] = {
{"\145\170\160\157\162\164",0,0,6,51,NULL},
};
static const gravity_aot_attribute_value ga_attr_value_3 = {.kind=1,.count=0,.text="\156\141\164\151\166\145\056\141\163\171\156\143"};
static const gravity_aot_attribute_argument ga_args_3_0[] = {
{"\151\144",&ga_attr_value_3},
};
static const gravity_aot_attribute ga_attrs_3[] = {
{"\163\171\163\164\145\155",1,0,7,1,ga_args_3_0},
};
static const gravity_aot_attribute_value ga_attr_value_4 = {.kind=0,.count=0,.text="\116\141\164\151\166\145\101\163\171\156\143\123\164\141\164\163"};
static const gravity_aot_attribute_argument ga_args_4_0[] = {
{NULL,&ga_attr_value_4},
};
static const gravity_aot_attribute ga_attrs_4[] = {
{"\162\145\163\157\165\162\143\145",1,0,9,5,ga_args_4_0},
};
static const gravity_aot_parameter ga_params_8[] = {
{"\166\141\154\165\145",NULL},
};
static const gravity_aot_parameter ga_params_10[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_attribute_value ga_attr_value_5 = {.kind=1,.count=0,.text="\141\157\164\056\141\163\171\156\143\056\143\157\156\164\162\157\154\154\145\162"};
static const gravity_aot_attribute_value ga_attr_value_6 = {.kind=2,.count=0,.integer=(int64_t)UINT64_C(1)};
static const gravity_aot_attribute_argument ga_args_11_0[] = {
{"\151\144",&ga_attr_value_5},
{"\166\145\162\163\151\157\156",&ga_attr_value_6},
};
static const gravity_aot_attribute ga_attrs_11[] = {
{"\163\143\162\151\160\164\141\142\154\145",2,0,26,1,ga_args_11_0},
};
static const gravity_aot_attribute ga_attrs_12[] = {
{"\145\170\160\157\162\164",0,0,28,5,NULL},
};
static const gravity_aot_parameter ga_params_13[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_19[] = {
{"\166\141\154\165\145\163",NULL},
};
static const gravity_aot_parameter ga_params_24[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_26[] = {
{"\166\141\154\165\145",NULL},
};
static const gravity_aot_parameter ga_params_30[] = {
{"\160\141\164\150",NULL},
};
static const gravity_aot_declaration ga_ada_native_async_declarations[] = {
{"\116\141\164\151\166\145\101\163\171\156\143\123\164\141\164\163",NULL,NULL,2,0,6,1,1,ga_attrs_0,0,NULL},
{"\162\145\163\165\154\164","\116\141\164\151\166\145\101\163\171\156\143\123\164\141\164\163",NULL,3,0,6,39,1,ga_attrs_1,0,NULL},
{"\144\157\156\145","\116\141\164\151\166\145\101\163\171\156\143\123\164\141\164\163",NULL,3,0,6,63,1,ga_attrs_2,0,NULL},
{"\116\141\164\151\166\145\101\163\171\156\143\123\171\163\164\145\155",NULL,NULL,1,0,8,1,1,ga_attrs_3,0,NULL},
{"\163\164\141\164\163","\116\141\164\151\166\145\101\163\171\156\143\123\171\163\164\145\155",NULL,3,0,9,37,1,ga_attrs_4,0,NULL},
{"\163\164\141\162\164\145\144","\116\141\164\151\166\145\101\163\171\156\143\123\171\163\164\145\155",NULL,3,0,10,9,0,NULL,0,NULL},
{"\163\165\155","\116\141\164\151\166\145\101\163\171\156\143\123\171\163\164\145\155",NULL,3,0,11,9,0,NULL,0,NULL},
{"\141\156\163\167\145\162","\116\141\164\151\166\145\101\163\171\156\143\123\171\163\164\145\155",NULL,3,0,12,9,0,NULL,0,NULL},
{"\143\150\151\154\144","\116\141\164\151\166\145\101\163\171\156\143\123\171\163\164\145\155",NULL,4,0,13,11,0,NULL,1,ga_params_8},
{"\141\144\166\141\156\143\145","\116\141\164\151\166\145\101\163\171\156\143\123\171\163\164\145\155",NULL,4,0,14,11,0,NULL,0,NULL},
{"\165\160\144\141\164\145","\116\141\164\151\166\145\101\163\171\156\143\123\171\163\164\145\155",NULL,4,0,21,5,0,NULL,1,ga_params_10},
{"\116\141\164\151\166\145\101\163\171\156\143\103\157\156\164\162\157\154\154\145\162",NULL,NULL,1,0,27,1,1,ga_attrs_11,0,NULL},
{"\146\162\141\155\145\163","\116\141\164\151\166\145\101\163\171\156\143\103\157\156\164\162\157\154\154\145\162",NULL,3,0,28,17,1,ga_attrs_12,0,NULL},
{"\162\145\141\144\171","\116\141\164\151\166\145\101\163\171\156\143\103\157\156\164\162\157\154\154\145\162",NULL,4,0,29,5,0,NULL,1,ga_params_13},
{"\141\144\166\141\156\143\145","\116\141\164\151\166\145\101\163\171\156\143\103\157\156\164\162\157\154\154\145\162",NULL,4,0,30,11,0,NULL,0,NULL},
{"\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,NULL,1,0,34,1,0,NULL,0,NULL},
{"\143\157\165\156\164\145\162","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,3,0,35,9,0,NULL,0,NULL},
{"\157\162\144\145\162","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,3,0,36,9,0,NULL,0,NULL},
{"\162\145\164\141\151\156\145\144","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,3,0,37,9,0,NULL,0,NULL},
{"\162\145\164\141\151\156","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,38,5,0,NULL,1,ga_params_19},
{"\162\145\164\141\151\156\145\144\103\157\155\160\154\145\164\145","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,39,5,0,NULL,0,NULL},
{"\143\154\145\141\162\122\145\164\141\151\156\145\144","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,40,5,0,NULL,0,NULL},
{"\142\145\147\151\156","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,41,5,0,NULL,0,NULL},
{"\157\162\144\145\162\145\144","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,42,11,0,NULL,0,NULL},
{"\163\164\141\154\145","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,43,11,0,NULL,1,ga_params_24},
{"\156\145\163\164\145\144","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,44,11,0,NULL,0,NULL},
{"\143\150\151\154\144","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,45,11,0,NULL,1,ga_params_26},
{"\154\157\156\147\114\157\157\160","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,46,11,0,NULL,0,NULL},
{"\151\155\155\145\144\151\141\164\145","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,47,11,0,NULL,0,NULL},
{"\151\156\146\151\156\151\164\145","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,48,11,0,NULL,0,NULL},
{"\154\157\141\144","\116\141\164\151\166\145\101\163\171\156\143\120\162\157\142\145",NULL,4,0,49,11,0,NULL,1,ga_params_30},
};
static const gravity_aot_field ga_fields_0[] = {
{&ga_ada_native_async_declarations[1],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
{&ga_ada_native_async_declarations[2],{.integer=0,.kind=GRAVITY_AOT_BOOL},0,NULL},
};
static const gravity_aot_field ga_fields_1[] = {
{&ga_ada_native_async_declarations[4],{0},0,NULL},
{&ga_ada_native_async_declarations[5],{.integer=0,.kind=GRAVITY_AOT_BOOL},0,NULL},
{&ga_ada_native_async_declarations[6],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
{&ga_ada_native_async_declarations[7],{0},0,ada_native_async_field_7},
};
static const gravity_aot_method_export ga_methods_1[] = {
{"\143\150\151\154\144",1,ada_native_async_fn_8,&ga_ada_native_async_declarations[8]},
{"\141\144\166\141\156\143\145",0,ada_native_async_fn_9,&ga_ada_native_async_declarations[9]},
{"\165\160\144\141\164\145",1,ada_native_async_fn_10,&ga_ada_native_async_declarations[10]},
};
static const gravity_aot_field ga_fields_2[] = {
{&ga_ada_native_async_declarations[12],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
};
static const gravity_aot_method_export ga_methods_2[] = {
{"\162\145\141\144\171",1,ada_native_async_fn_13,&ga_ada_native_async_declarations[13]},
{"\141\144\166\141\156\143\145",0,ada_native_async_fn_14,&ga_ada_native_async_declarations[14]},
};
static const gravity_aot_field ga_fields_3[] = {
{&ga_ada_native_async_declarations[16],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
{&ga_ada_native_async_declarations[17],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
{&ga_ada_native_async_declarations[18],{0},0,NULL},
};
static const gravity_aot_method_export ga_methods_3[] = {
{"\162\145\164\141\151\156",1,ada_native_async_fn_19,&ga_ada_native_async_declarations[19]},
{"\162\145\164\141\151\156\145\144\103\157\155\160\154\145\164\145",0,ada_native_async_fn_20,&ga_ada_native_async_declarations[20]},
{"\143\154\145\141\162\122\145\164\141\151\156\145\144",0,ada_native_async_fn_21,&ga_ada_native_async_declarations[21]},
{"\142\145\147\151\156",0,ada_native_async_fn_22,&ga_ada_native_async_declarations[22]},
{"\157\162\144\145\162\145\144",0,ada_native_async_fn_23,&ga_ada_native_async_declarations[23]},
{"\163\164\141\154\145",1,ada_native_async_fn_24,&ga_ada_native_async_declarations[24]},
{"\156\145\163\164\145\144",0,ada_native_async_fn_25,&ga_ada_native_async_declarations[25]},
{"\143\150\151\154\144",1,ada_native_async_fn_26,&ga_ada_native_async_declarations[26]},
{"\154\157\156\147\114\157\157\160",0,ada_native_async_fn_27,&ga_ada_native_async_declarations[27]},
{"\151\155\155\145\144\151\141\164\145",0,ada_native_async_fn_28,&ga_ada_native_async_declarations[28]},
{"\151\156\146\151\156\151\164\145",0,ada_native_async_fn_29,&ga_ada_native_async_declarations[29]},
{"\154\157\141\144",1,ada_native_async_fn_30,&ga_ada_native_async_declarations[30]},
};
static const gravity_aot_class ga_ada_native_async_types[4] = {
{&ga_ada_native_async_declarations[0],1,2,0,ga_fields_0,NULL},
{&ga_ada_native_async_declarations[3],0,4,3,ga_fields_1,ga_methods_1},
{&ga_ada_native_async_declarations[11],0,1,2,ga_fields_2,ga_methods_2},
{&ga_ada_native_async_declarations[15],0,3,12,ga_fields_3,ga_methods_3},
};
const gravity_aot_module *ada_native_async_get_module(void) {
static const gravity_aot_module m={GRAVITY_AOT_ABI_VERSION,0,NULL,4,31,ga_ada_native_async_types,ga_ada_native_async_declarations};
return &m;
}
