/* Generated by Gravity AOT; standalone ABI 3. */
#include <shared/gravity_aot_runtime.h>
static const gravity_aot_class ga_ada_native_hosts_types[5];
static gravity_aot_value ada_native_hosts_fn_14(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_hosts_fn_15(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_hosts_fn_17(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_hosts_fn_18(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_hosts_fn_19(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static void ada_native_hosts_resume_14(gravity_aot_context *ctx, gravity_aot_task *task) {
gravity_aot_value result=gravity_aot_null();
switch (task->pc) {
case 0: break;
case 1: goto ga_resume_1;
default: gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit;
}
{
task->values[7] = gravity_aot_get(ctx,gravity_aot_null(),"\124\141\163\153\163");
if (ctx->error) goto ga_exit;
(void)task->values[7];
 (void)(&task->values[18]);
task->values[8]=gravity_aot_call(ctx,task->values[7],"\156\145\170\164\106\162\141\155\145",(&task->values[18]),0);
if (ctx->error) goto ga_exit;
task->values[6]=task->values[8];
(void)task->values[6];
task->waiting=task->values[6]; task->pc=1;
ga_resume_1:;
task->values[5]=gravity_aot_null();
if (!gravity_aot_task_poll(ctx,task->waiting,&task->values[5])) goto ga_suspend;
if (ctx->error) goto ga_exit;
task->waiting=gravity_aot_null(); task->pc=0;
(void)task->values[5];
task->values[11] = task->values[2];
(void)task->values[11];
task->values[13] = gravity_aot_field_get(ctx,task->values[0],1);
if (ctx->error) goto ga_exit;
(void)task->values[13];
(void)gravity_aot_set(ctx,task->values[13],"\141\163\171\156\143\101\155\157\165\156\164",task->values[11]);
if (ctx->error) goto ga_exit;
task->values[10] = task->values[11];
(void)task->values[10];
task->values[15] = task->values[1];
(void)task->values[15];
task->values[17] = gravity_aot_field_get(ctx,task->values[0],1);
if (ctx->error) goto ga_exit;
(void)task->values[17];
(void)gravity_aot_set(ctx,task->values[17],"\163\145\156\144\145\162",task->values[15]);
if (ctx->error) goto ga_exit;
task->values[14] = task->values[15];
(void)task->values[14];
}
goto ga_exit;
ga_exit: task->result=result; task->error=ctx->error; task->state=ctx->error?GA_TASK_FAILED:GA_TASK_COMPLETE;
return;
ga_suspend: if (ctx->error) { task->error=ctx->error; task->state=GA_TASK_FAILED; } else task->state=GA_TASK_PENDING;
}
static gravity_aot_value ada_native_hosts_fn_14(gravity_aot_context *ctx,gravity_aot_value receiver, const gravity_aot_value *args,uint32_t argc) {
if (!ctx) return gravity_aot_null();
if (argc!=2 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return gravity_aot_null(); }
gravity_aot_value value=gravity_aot_task_new(ctx,ada_native_hosts_resume_14,19,14);
if (ctx->error) return gravity_aot_null();
gravity_aot_task *task=value.task; (void)task;
task->values[0]=receiver;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_hosts_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); return gravity_aot_null(); }
task->values[1]=gravity_aot_copy(ctx,args[0]);
task->values[2]=gravity_aot_copy(ctx,args[1]);
return ctx->error?gravity_aot_null():value;
}
static gravity_aot_value ada_native_hosts_fn_15(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_hosts_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t3 = gravity_aot_field_get(ctx,v0,3);
if (ctx->error) goto ga_exit;
(void)t3;
gravity_aot_value t2 = gravity_aot_unary(ctx, 14, t3);
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value t5 = gravity_aot_field_get(ctx,v0,0);
if (ctx->error) goto ga_exit;
(void)t5;
gravity_aot_value a7[1]; (void)a7;
gravity_aot_value t6=gravity_aot_call(ctx,t5,"\141\166\141\151\154\141\142\154\145",a7,0);
if (ctx->error) goto ga_exit;
gravity_aot_value t4=t6;
(void)t4;
gravity_aot_value t1 = gravity_aot_binary(ctx, 11, t2, t4);
if (ctx->error) goto ga_exit;
(void)t1;
if (gravity_aot_truth(ctx, t1)) {
{
gravity_aot_value t10 = v1;
(void)t10;
gravity_aot_value t11=gravity_aot_get(ctx,t10,"\167\157\162\154\144");
if (ctx->error) goto ga_exit;
gravity_aot_value a13[1]; (void)a13;
gravity_aot_value a14[1]; (void)a14;
gravity_aot_value t16 = gravity_aot_get(ctx,gravity_aot_null(),"\137\137\141\144\141\103\157\155\160\157\156\145\156\164\106\141\143\164\157\162\171");
if (ctx->error) goto ga_exit;
(void)t16;
gravity_aot_value a18[2]; (void)a18;
gravity_aot_value t19 = gravity_aot_string("\110\157\163\164\120\157\163\151\164\151\157\156", 12);
(void)t19;
a18[0]=gravity_aot_copy(ctx,t19);
if (ctx->error) goto ga_exit;
gravity_aot_value a20[1]; (void)a20;
gravity_aot_value t21 = gravity_aot_null();
(void)t21;
a20[0]=gravity_aot_copy(ctx,t21);
if (ctx->error) goto ga_exit;
gravity_aot_value t20 = gravity_aot_list_new(ctx,a20,1);
if (ctx->error) goto ga_exit;
(void)t20;
a18[1]=gravity_aot_copy(ctx,t20);
if (ctx->error) goto ga_exit;
gravity_aot_value t17=gravity_aot_call(ctx,t16,"\155\141\153\145\116\141\155\145\144",a18,2);
if (ctx->error) goto ga_exit;
gravity_aot_value t15=t17;
(void)t15;
a14[0]=gravity_aot_copy(ctx,t15);
if (ctx->error) goto ga_exit;
gravity_aot_value t14 = gravity_aot_list_new(ctx,a14,1);
if (ctx->error) goto ga_exit;
(void)t14;
a13[0]=gravity_aot_copy(ctx,t14);
if (ctx->error) goto ga_exit;
gravity_aot_value t12=gravity_aot_call(ctx,t11,"\163\160\141\167\156",a13,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t9=t12;
(void)t9;
gravity_aot_value t23 = gravity_aot_field_get(ctx,v0,1);
if (ctx->error) goto ga_exit;
(void)t23;
(void)gravity_aot_set(ctx,t23,"\163\160\141\167\156\145\144",t9);
if (ctx->error) goto ga_exit;
gravity_aot_value t8 = t9;
(void)t8;
gravity_aot_value t25 = gravity_aot_get(ctx,gravity_aot_null(),"\137\137\141\144\141\116\145\164\167\157\162\153\106\141\143\164\157\162\171");
if (ctx->error) goto ga_exit;
(void)t25;
gravity_aot_value a27[2]; (void)a27;
gravity_aot_value t28 = gravity_aot_string("\110\157\163\164\115\157\166\145", 8);
(void)t28;
a27[0]=gravity_aot_copy(ctx,t28);
if (ctx->error) goto ga_exit;
gravity_aot_value a29[1]; (void)a29;
gravity_aot_value t30 = gravity_aot_null();
(void)t30;
a29[0]=gravity_aot_copy(ctx,t30);
if (ctx->error) goto ga_exit;
gravity_aot_value t29 = gravity_aot_list_new(ctx,a29,1);
if (ctx->error) goto ga_exit;
(void)t29;
a27[1]=gravity_aot_copy(ctx,t29);
if (ctx->error) goto ga_exit;
gravity_aot_value t26=gravity_aot_call(ctx,t25,"\155\141\153\145\116\141\155\145\144",a27,2);
if (ctx->error) goto ga_exit;
gravity_aot_value t24=t26;
(void)t24;
gravity_aot_value v2 = gravity_aot_copy(ctx,t24); (void)v2;
if (ctx->error) goto ga_exit;
gravity_aot_value t32 = gravity_aot_int((int64_t)UINT64_C(27));
(void)t32;
gravity_aot_value t34 = v2;
(void)t34;
(void)gravity_aot_set(ctx,t34,"\141\155\157\165\156\164",t32);
if (ctx->error) goto ga_exit;
gravity_aot_value t31 = t32;
(void)t31;
gravity_aot_value t36 = gravity_aot_get(ctx,gravity_aot_null(),"\155\165\154\164\151\160\154\141\171\145\162");
if (ctx->error) goto ga_exit;
(void)t36;
gravity_aot_value a38[1]; (void)a38;
gravity_aot_value t39 = v2;
(void)t39;
a38[0]=gravity_aot_copy(ctx,t39);
if (ctx->error) goto ga_exit;
gravity_aot_value t37=gravity_aot_call(ctx,t36,"\163\145\156\144",a38,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t35=t37;
(void)t35;
gravity_aot_value t41 = gravity_aot_get(ctx,gravity_aot_null(),"\155\165\154\164\151\160\154\141\171\145\162");
if (ctx->error) goto ga_exit;
(void)t41;
gravity_aot_value a43[1]; (void)a43;
gravity_aot_value t45 = gravity_aot_get(ctx,gravity_aot_null(),"\137\137\141\144\141\116\145\164\167\157\162\153\106\141\143\164\157\162\171");
if (ctx->error) goto ga_exit;
(void)t45;
gravity_aot_value a47[2]; (void)a47;
gravity_aot_value t48 = gravity_aot_string("\101\163\171\156\143\115\157\166\145", 9);
(void)t48;
a47[0]=gravity_aot_copy(ctx,t48);
if (ctx->error) goto ga_exit;
gravity_aot_value a49[1]; (void)a49;
gravity_aot_value t50 = gravity_aot_int((int64_t)UINT64_C(41));
(void)t50;
a49[0]=gravity_aot_copy(ctx,t50);
if (ctx->error) goto ga_exit;
gravity_aot_value t49 = gravity_aot_list_new(ctx,a49,1);
if (ctx->error) goto ga_exit;
(void)t49;
a47[1]=gravity_aot_copy(ctx,t49);
if (ctx->error) goto ga_exit;
gravity_aot_value t46=gravity_aot_call(ctx,t45,"\155\141\153\145\116\141\155\145\144",a47,2);
if (ctx->error) goto ga_exit;
gravity_aot_value t44=t46;
(void)t44;
a43[0]=gravity_aot_copy(ctx,t44);
if (ctx->error) goto ga_exit;
gravity_aot_value t42=gravity_aot_call(ctx,t41,"\163\145\156\144",a43,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t40=t42;
(void)t40;
gravity_aot_value t52 = gravity_aot_bool(1);
(void)t52;
(void)gravity_aot_field_set(ctx,v0,3,t52);
if (ctx->error) goto ga_exit;
gravity_aot_value t51 = t52;
(void)t51;
}
}
if (ctx->error) goto ga_exit;
gravity_aot_value t53 = gravity_aot_field_get(ctx,v0,2);
if (ctx->error) goto ga_exit;
(void)t53;
{ uint64_t state54=0; gravity_aot_value v3=gravity_aot_null(); (void)v3;
while (1) {
if (!gravity_aot_tick(ctx)) goto ga_exit;
int next54=gravity_aot_next(ctx,t53,&state54,&v3);
if (ctx->error) goto ga_exit;
if (!next54) break;
v3=gravity_aot_copy(ctx,v3);
if (ctx->error) goto ga_exit;
{
gravity_aot_value t57 = v3;
(void)t57;
gravity_aot_value t58=gravity_aot_get(ctx,t57,"\166\141\154\165\145");
if (ctx->error) goto ga_exit;
gravity_aot_value t59=gravity_aot_get(ctx,t58,"\141\155\157\165\156\164");
if (ctx->error) goto ga_exit;
gravity_aot_value t56=t59;
(void)t56;
gravity_aot_value t61 = gravity_aot_field_get(ctx,v0,1);
if (ctx->error) goto ga_exit;
(void)t61;
(void)gravity_aot_set(ctx,t61,"\141\155\157\165\156\164",t56);
if (ctx->error) goto ga_exit;
gravity_aot_value t55 = t56;
(void)t55;
}
} }
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_hosts_fn_17(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_hosts_types[4]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t2 = gravity_aot_get(ctx,gravity_aot_null(),"\101\163\163\145\164\163");
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value a4[2]; (void)a4;
gravity_aot_value t5 = gravity_aot_string("\116\141\164\151\166\145\123\143\162\151\160\164\101\163\163\145\164", 17);
(void)t5;
a4[0]=gravity_aot_copy(ctx,t5);
if (ctx->error) goto ga_exit;
gravity_aot_value t6 = gravity_aot_string("\100\162\145\163\072\057\057\160\162\157\142\145\056\156\141\164\151\166\145\141\163\163\145\164", 24);
(void)t6;
a4[1]=gravity_aot_copy(ctx,t6);
if (ctx->error) goto ga_exit;
gravity_aot_value t3=gravity_aot_call(ctx,t2,"\154\157\141\144\124\171\160\145\144",a4,2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1=t3;
(void)t1;
result = t1; goto ga_exit;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_hosts_fn_18(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_hosts_types[4]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t2 = gravity_aot_get(ctx,gravity_aot_null(),"\137\137\141\144\141\101\163\163\145\164\163");
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value a4[1]; (void)a4;
gravity_aot_value a5[3]; (void)a5;
gravity_aot_value t6 = gravity_aot_string("\154\157\141\144\124\171\160\145\144", 9);
(void)t6;
a5[0]=gravity_aot_copy(ctx,t6);
if (ctx->error) goto ga_exit;
gravity_aot_value t7 = gravity_aot_string("\116\141\164\151\166\145\123\143\162\151\160\164\101\163\163\145\164", 17);
(void)t7;
a5[1]=gravity_aot_copy(ctx,t7);
if (ctx->error) goto ga_exit;
gravity_aot_value t8 = gravity_aot_string("\100\162\145\163\072\057\057\160\162\157\142\145\056\156\141\164\151\166\145\141\163\163\145\164", 24);
(void)t8;
a5[2]=gravity_aot_copy(ctx,t8);
if (ctx->error) goto ga_exit;
gravity_aot_value t5 = gravity_aot_list_new(ctx,a5,3);
if (ctx->error) goto ga_exit;
(void)t5;
a4[0]=gravity_aot_copy(ctx,t5);
if (ctx->error) goto ga_exit;
gravity_aot_value t3=gravity_aot_call(ctx,t2,"\160\145\162\146\157\162\155",a4,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t1=t3;
(void)t1;
gravity_aot_value v2 = gravity_aot_copy(ctx,t1); (void)v2;
if (ctx->error) goto ga_exit;
gravity_aot_value t10 = gravity_aot_get(ctx,gravity_aot_null(),"\137\137\141\144\141\101\163\163\145\164\163");
if (ctx->error) goto ga_exit;
(void)t10;
gravity_aot_value a12[1]; (void)a12;
gravity_aot_value a13[3]; (void)a13;
gravity_aot_value t14 = gravity_aot_string("\163\141\166\145", 4);
(void)t14;
a13[0]=gravity_aot_copy(ctx,t14);
if (ctx->error) goto ga_exit;
gravity_aot_value t15 = v2;
(void)t15;
a13[1]=gravity_aot_copy(ctx,t15);
if (ctx->error) goto ga_exit;
gravity_aot_value t16 = gravity_aot_string("\100\165\163\145\162\072\057\057\143\157\160\171\056\156\141\164\151\166\145\141\163\163\145\164", 24);
(void)t16;
a13[2]=gravity_aot_copy(ctx,t16);
if (ctx->error) goto ga_exit;
gravity_aot_value t13 = gravity_aot_list_new(ctx,a13,3);
if (ctx->error) goto ga_exit;
(void)t13;
a12[0]=gravity_aot_copy(ctx,t13);
if (ctx->error) goto ga_exit;
gravity_aot_value t11=gravity_aot_call(ctx,t10,"\160\145\162\146\157\162\155",a12,1);
if (ctx->error) goto ga_exit;
gravity_aot_value t9=t11;
(void)t9;
result = t9; goto ga_exit;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_hosts_fn_19(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_hosts_types[4]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t2 = v1;
(void)t2;
gravity_aot_value t3=gravity_aot_get(ctx,t2,"\167\157\162\154\144");
if (ctx->error) goto ga_exit;
gravity_aot_value a5[1]; (void)a5;
gravity_aot_value t4=gravity_aot_call(ctx,t3,"\162\145\154\157\141\144\123\143\145\156\145",a5,0);
if (ctx->error) goto ga_exit;
gravity_aot_value t1=t4;
(void)t1;
result = t1; goto ga_exit;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static const gravity_aot_attribute_value ga_attr_value_1 = {.kind=1,.count=0,.text="\141\157\164\056\150\157\163\164\056\160\157\163\151\164\151\157\156"};
static const gravity_aot_attribute_argument ga_args_0_0[] = {
{"\151\144",&ga_attr_value_1},
};
static const gravity_aot_attribute ga_attrs_0[] = {
{"\143\157\155\160\157\156\145\156\164",1,0,9,1,ga_args_0_0},
};
static const gravity_aot_attribute ga_attrs_1[] = {
{"\145\170\160\157\162\164",0,0,10,23,NULL},
};
static const gravity_aot_attribute_value ga_attr_value_2 = {.kind=1,.count=0,.text="\141\157\164\056\150\157\163\164\056\155\157\166\145"};
static const gravity_aot_attribute_value ga_attr_value_3 = {.kind=1,.count=0,.text="\165\156\162\145\154\151\141\142\154\145\137\163\145\161\165\145\156\143\145\144"};
static const gravity_aot_attribute_value ga_attr_value_4 = {.kind=1,.count=0,.text="\151\156\160\165\164"};
static const gravity_aot_attribute_argument ga_args_2_0[] = {
{"\151\144",&ga_attr_value_2},
{"\144\145\154\151\166\145\162\171",&ga_attr_value_3},
{"\143\150\141\156\156\145\154",&ga_attr_value_4},
};
static const gravity_aot_attribute ga_attrs_2[] = {
{"\156\145\164\167\157\162\153\137\143\157\155\155\141\156\144",3,0,11,1,ga_args_2_0},
};
static const gravity_aot_attribute_value ga_attr_value_5 = {.kind=2,.count=0,.integer=(int64_t)UINT64_C(1)};
static const gravity_aot_attribute_argument ga_args_3_0[] = {
{NULL,&ga_attr_value_5},
};
static const gravity_aot_attribute ga_attrs_3[] = {
{"\156\145\164\167\157\162\153\137\146\151\145\154\144",1,0,12,19,ga_args_3_0},
};
static const gravity_aot_attribute_value ga_attr_value_6 = {.kind=1,.count=0,.text="\141\157\164\056\150\157\163\164\056\143\141\160\164\165\162\145"};
static const gravity_aot_attribute_value ga_attr_value_7 = {.kind=4,.count=0,.integer=1};
static const gravity_aot_attribute_argument ga_args_4_0[] = {
{"\151\144",&ga_attr_value_6},
{"\141\165\164\157\111\156\163\145\162\164",&ga_attr_value_7},
};
static const gravity_aot_attribute ga_attrs_4[] = {
{"\162\145\163\157\165\162\143\145",2,0,13,1,ga_args_4_0},
};
static const gravity_aot_attribute ga_attrs_5[] = {
{"\145\170\160\157\162\164",0,0,14,22,NULL},
};
static const gravity_aot_attribute ga_attrs_6[] = {
{"\145\170\160\157\162\164",0,0,14,46,NULL},
};
static const gravity_aot_attribute ga_attrs_7[] = {
{"\145\170\160\157\162\164",0,0,14,72,NULL},
};
static const gravity_aot_attribute ga_attrs_8[] = {
{"\145\170\160\157\162\164",0,0,14,101,NULL},
};
static const gravity_aot_attribute_value ga_attr_value_8 = {.kind=1,.count=0,.text="\141\157\164\056\150\157\163\164\056\163\171\163\164\145\155"};
static const gravity_aot_attribute_argument ga_args_9_0[] = {
{"\151\144",&ga_attr_value_8},
};
static const gravity_aot_attribute ga_attrs_9[] = {
{"\163\171\163\164\145\155",1,0,15,1,ga_args_9_0},
};
static const gravity_aot_attribute_value ga_attr_value_9 = {.kind=0,.count=0,.text="\111\156\160\165\164"};
static const gravity_aot_attribute_argument ga_args_10_0[] = {
{NULL,&ga_attr_value_9},
};
static const gravity_aot_attribute ga_attrs_10[] = {
{"\162\145\163\157\165\162\143\145",1,0,17,5,ga_args_10_0},
};
static const gravity_aot_attribute_value ga_attr_value_10 = {.kind=0,.count=0,.text="\110\157\163\164\103\141\160\164\165\162\145"};
static const gravity_aot_attribute_argument ga_args_11_0[] = {
{NULL,&ga_attr_value_10},
};
static const gravity_aot_attribute ga_attrs_11[] = {
{"\162\145\163\157\165\162\143\145",1,0,18,5,ga_args_11_0},
};
static const gravity_aot_attribute_value ga_attr_value_11 = {.kind=0,.count=0,.text="\110\157\163\164\115\157\166\145"};
static const gravity_aot_attribute_argument ga_args_12_0[] = {
{NULL,&ga_attr_value_11},
};
static const gravity_aot_attribute ga_attrs_12[] = {
{"\162\145\155\157\164\145\137\143\157\155\155\141\156\144\163",1,0,19,5,ga_args_12_0},
};
static const gravity_aot_attribute_value ga_attr_value_12 = {.kind=1,.count=0,.text="\141\157\164\056\150\157\163\164\056\141\163\171\156\143\137\155\157\166\145"};
static const gravity_aot_attribute_argument ga_args_14_0[] = {
{"\151\144",&ga_attr_value_12},
};
static const gravity_aot_parameter ga_params_14[] = {
{"\163\157\165\162\143\145",NULL},
{"\141\155\157\165\156\164",NULL},
};
static const gravity_aot_attribute ga_attrs_14[] = {
{"\162\160\143",1,0,21,5,ga_args_14_0},
};
static const gravity_aot_parameter ga_params_15[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_17[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_18[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_19[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_declaration ga_ada_native_hosts_declarations[] = {
{"\110\157\163\164\120\157\163\151\164\151\157\156",NULL,NULL,2,0,10,1,1,ga_attrs_0,0,NULL},
{"\166\141\154\165\145","\110\157\163\164\120\157\163\151\164\151\157\156",NULL,3,0,10,35,1,ga_attrs_1,0,NULL},
{"\110\157\163\164\115\157\166\145",NULL,NULL,2,0,12,1,1,ga_attrs_2,0,NULL},
{"\141\155\157\165\156\164","\110\157\163\164\115\157\166\145",NULL,3,0,12,41,1,ga_attrs_3,0,NULL},
{"\110\157\163\164\103\141\160\164\165\162\145",NULL,NULL,2,0,14,1,1,ga_attrs_4,0,NULL},
{"\141\155\157\165\156\164","\110\157\163\164\103\141\160\164\165\162\145",NULL,3,0,14,34,1,ga_attrs_5,0,NULL},
{"\163\160\141\167\156\145\144","\110\157\163\164\103\141\160\164\165\162\145",NULL,3,0,14,58,1,ga_attrs_6,0,NULL},
{"\141\163\171\156\143\101\155\157\165\156\164","\110\157\163\164\103\141\160\164\165\162\145",NULL,3,0,14,84,1,ga_attrs_7,0,NULL},
{"\163\145\156\144\145\162","\110\157\163\164\103\141\160\164\165\162\145",NULL,3,0,14,113,1,ga_attrs_8,0,NULL},
{"\110\157\163\164\123\171\163\164\145\155",NULL,NULL,1,0,16,1,1,ga_attrs_9,0,NULL},
{"\151\156\160\165\164","\110\157\163\164\123\171\163\164\145\155",NULL,3,0,17,26,1,ga_attrs_10,0,NULL},
{"\143\141\160\164\165\162\145","\110\157\163\164\123\171\163\164\145\155",NULL,3,0,18,32,1,ga_attrs_11,0,NULL},
{"\162\145\143\145\151\166\145\144","\110\157\163\164\123\171\163\164\145\155",NULL,3,0,19,36,1,ga_attrs_12,0,NULL},
{"\163\145\156\164","\110\157\163\164\123\171\163\164\145\155",NULL,3,0,20,9,0,NULL,0,NULL},
{"\101\163\171\156\143\115\157\166\145","\110\157\163\164\123\171\163\164\145\155",NULL,4,0,21,43,1,ga_attrs_14,2,ga_params_14},
{"\165\160\144\141\164\145","\110\157\163\164\123\171\163\164\145\155",NULL,4,0,26,5,0,NULL,1,ga_params_15},
{"\110\157\163\164\120\162\157\142\145",NULL,NULL,1,0,38,1,0,NULL,0,NULL},
{"\154\157\141\144","\110\157\163\164\120\162\157\142\145",NULL,4,0,39,5,0,NULL,1,ga_params_17},
{"\163\141\166\145","\110\157\163\164\120\162\157\142\145",NULL,4,0,40,5,0,NULL,1,ga_params_18},
{"\163\164\141\154\145","\110\157\163\164\120\162\157\142\145",NULL,4,0,44,5,0,NULL,1,ga_params_19},
};
static const gravity_aot_field ga_fields_0[] = {
{&ga_ada_native_hosts_declarations[1],{.floating=0x1.4p+2,.kind=GRAVITY_AOT_FLOAT},0,NULL},
};
static const gravity_aot_field ga_fields_1[] = {
{&ga_ada_native_hosts_declarations[3],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
};
static const gravity_aot_field ga_fields_2[] = {
{&ga_ada_native_hosts_declarations[5],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
{&ga_ada_native_hosts_declarations[6],{.integer=(int64_t)UINT64_C(18446744073709551615),.kind=1},0,NULL},
{&ga_ada_native_hosts_declarations[7],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
{&ga_ada_native_hosts_declarations[8],{.string="",.kind=GRAVITY_AOT_STRING,.length=0},0,NULL},
};
static const gravity_aot_field ga_fields_3[] = {
{&ga_ada_native_hosts_declarations[10],{0},0,NULL},
{&ga_ada_native_hosts_declarations[11],{0},0,NULL},
{&ga_ada_native_hosts_declarations[12],{0},0,NULL},
{&ga_ada_native_hosts_declarations[13],{.integer=0,.kind=GRAVITY_AOT_BOOL},0,NULL},
};
static const gravity_aot_method_export ga_methods_3[] = {
{"\101\163\171\156\143\115\157\166\145",2,ada_native_hosts_fn_14,&ga_ada_native_hosts_declarations[14]},
{"\165\160\144\141\164\145",1,ada_native_hosts_fn_15,&ga_ada_native_hosts_declarations[15]},
};
static const gravity_aot_method_export ga_methods_4[] = {
{"\154\157\141\144",1,ada_native_hosts_fn_17,&ga_ada_native_hosts_declarations[17]},
{"\163\141\166\145",1,ada_native_hosts_fn_18,&ga_ada_native_hosts_declarations[18]},
{"\163\164\141\154\145",1,ada_native_hosts_fn_19,&ga_ada_native_hosts_declarations[19]},
};
static const gravity_aot_class ga_ada_native_hosts_types[5] = {
{&ga_ada_native_hosts_declarations[0],1,1,0,ga_fields_0,NULL},
{&ga_ada_native_hosts_declarations[2],1,1,0,ga_fields_1,NULL},
{&ga_ada_native_hosts_declarations[4],1,4,0,ga_fields_2,NULL},
{&ga_ada_native_hosts_declarations[9],0,4,2,ga_fields_3,ga_methods_3},
{&ga_ada_native_hosts_declarations[16],0,0,3,NULL,ga_methods_4},
};
const gravity_aot_module *ada_native_hosts_get_module(void) {
static const gravity_aot_module m={GRAVITY_AOT_ABI_VERSION,0,NULL,5,20,ga_ada_native_hosts_types,ga_ada_native_hosts_declarations};
return &m;
}
