/* Generated by Gravity AOT; standalone ABI 3. */
#include <shared/gravity_aot_runtime.h>
static const gravity_aot_class ga_ada_native_fixture_types[5];
static gravity_aot_value ada_native_fixture_fn_6(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_fixture_fn_11(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_fixture_fn_16(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_fixture_fn_17(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_fixture_fn_18(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_fixture_fn_19(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_fixture_fn_20(gravity_aot_context *, gravity_aot_value, const gravity_aot_value *, uint32_t);
static gravity_aot_value ada_native_fixture_fn_6(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_fixture_types[2]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t4 = gravity_aot_field_get(ctx,v0,0);
if (ctx->error) goto ga_exit;
(void)t4;
gravity_aot_value t5=gravity_aot_get(ctx,t4,"\146\141\143\164\157\162");
if (ctx->error) goto ga_exit;
gravity_aot_value t3=t5;
(void)t3;
gravity_aot_value t6 = gravity_aot_float(0x1p+0);
(void)t6;
gravity_aot_value t2 = gravity_aot_binary(ctx, 0, t3, t6);
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value t8 = gravity_aot_field_get(ctx,v0,0);
if (ctx->error) goto ga_exit;
(void)t8;
(void)gravity_aot_set(ctx,t8,"\146\141\143\164\157\162",t2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1 = t2;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_fixture_fn_11(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_fixture_types[3]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t1 = gravity_aot_field_get(ctx,v0,0);
if (ctx->error) goto ga_exit;
(void)t1;
{ uint64_t state2=0; gravity_aot_value v2=gravity_aot_null(); (void)v2;
while (1) {
if (!gravity_aot_tick(ctx)) goto ga_exit;
int next2=gravity_aot_next(ctx,t1,&state2,&v2);
if (ctx->error) goto ga_exit;
if (!next2) break;
v2=gravity_aot_copy(ctx,v2);
if (ctx->error) goto ga_exit;
{
gravity_aot_value t6 = v2;
(void)t6;
gravity_aot_value t7=gravity_aot_get(ctx,t6,"\160\157\163\151\164\151\157\156\104\141\164\141");
if (ctx->error) goto ga_exit;
gravity_aot_value t8=gravity_aot_get(ctx,t7,"\166\141\154\165\145");
if (ctx->error) goto ga_exit;
gravity_aot_value t5=t8;
(void)t5;
gravity_aot_value t12 = v2;
(void)t12;
gravity_aot_value t13=gravity_aot_get(ctx,t12,"\156\141\164\151\166\145\126\145\154\157\143\151\164\171");
if (ctx->error) goto ga_exit;
gravity_aot_value t14=gravity_aot_get(ctx,t13,"\166\141\154\165\145");
if (ctx->error) goto ga_exit;
gravity_aot_value t11=t14;
(void)t11;
gravity_aot_value t16 = gravity_aot_field_get(ctx,v0,1);
if (ctx->error) goto ga_exit;
(void)t16;
gravity_aot_value t17=gravity_aot_get(ctx,t16,"\146\141\143\164\157\162");
if (ctx->error) goto ga_exit;
gravity_aot_value t15=t17;
(void)t15;
gravity_aot_value t10 = gravity_aot_binary(ctx, 2, t11, t15);
if (ctx->error) goto ga_exit;
(void)t10;
gravity_aot_value t19 = v1;
(void)t19;
gravity_aot_value t20=gravity_aot_get(ctx,t19,"\144\145\154\164\141\124\151\155\145");
if (ctx->error) goto ga_exit;
gravity_aot_value t18=t20;
(void)t18;
gravity_aot_value t9 = gravity_aot_binary(ctx, 2, t10, t18);
if (ctx->error) goto ga_exit;
(void)t9;
gravity_aot_value t4 = gravity_aot_binary(ctx, 0, t5, t9);
if (ctx->error) goto ga_exit;
(void)t4;
gravity_aot_value t22 = v2;
(void)t22;
gravity_aot_value t23=gravity_aot_get(ctx,t22,"\160\157\163\151\164\151\157\156\104\141\164\141");
if (ctx->error) goto ga_exit;
(void)gravity_aot_set(ctx,t23,"\166\141\154\165\145",t4);
if (ctx->error) goto ga_exit;
gravity_aot_value t3 = t4;
(void)t3;
}
} }
gravity_aot_value t26 = gravity_aot_field_get(ctx,v0,2);
if (ctx->error) goto ga_exit;
(void)t26;
gravity_aot_value t27 = gravity_aot_int((int64_t)UINT64_C(1));
(void)t27;
gravity_aot_value t25 = gravity_aot_binary(ctx, 0, t26, t27);
if (ctx->error) goto ga_exit;
(void)t25;
(void)gravity_aot_field_set(ctx,v0,2,t25);
if (ctx->error) goto ga_exit;
gravity_aot_value t24 = t25;
(void)t24;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_fixture_fn_16(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_fixture_types[4]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t3 = gravity_aot_field_get(ctx,v0,2);
if (ctx->error) goto ga_exit;
(void)t3;
gravity_aot_value t4 = gravity_aot_int((int64_t)UINT64_C(1));
(void)t4;
gravity_aot_value t2 = gravity_aot_binary(ctx, 0, t3, t4);
if (ctx->error) goto ga_exit;
(void)t2;
(void)gravity_aot_field_set(ctx,v0,2,t2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1 = t2;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_fixture_fn_17(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_fixture_types[4]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t4 = gravity_aot_field_get(ctx,v0,0);
if (ctx->error) goto ga_exit;
(void)t4;
gravity_aot_value t5=gravity_aot_get(ctx,t4,"\166\141\154\165\145");
if (ctx->error) goto ga_exit;
gravity_aot_value t3=t5;
(void)t3;
gravity_aot_value t7 = v1;
(void)t7;
gravity_aot_value t8=gravity_aot_get(ctx,t7,"\144\145\154\164\141\124\151\155\145");
if (ctx->error) goto ga_exit;
gravity_aot_value t6=t8;
(void)t6;
gravity_aot_value t2 = gravity_aot_binary(ctx, 0, t3, t6);
if (ctx->error) goto ga_exit;
(void)t2;
gravity_aot_value t10 = gravity_aot_field_get(ctx,v0,0);
if (ctx->error) goto ga_exit;
(void)t10;
(void)gravity_aot_set(ctx,t10,"\166\141\154\165\145",t2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1 = t2;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_fixture_fn_18(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_fixture_types[4]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t3 = gravity_aot_field_get(ctx,v0,2);
if (ctx->error) goto ga_exit;
(void)t3;
gravity_aot_value t4 = gravity_aot_int((int64_t)UINT64_C(1));
(void)t4;
gravity_aot_value t2 = gravity_aot_binary(ctx, 0, t3, t4);
if (ctx->error) goto ga_exit;
(void)t2;
(void)gravity_aot_field_set(ctx,v0,2,t2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1 = t2;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_fixture_fn_19(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=2 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_fixture_types[4]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
gravity_aot_value v2=gravity_aot_copy(ctx,args[1]); (void)v2;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t3 = gravity_aot_field_get(ctx,v0,2);
if (ctx->error) goto ga_exit;
(void)t3;
gravity_aot_value t4 = gravity_aot_int((int64_t)UINT64_C(2));
(void)t4;
gravity_aot_value t2 = gravity_aot_binary(ctx, 0, t3, t4);
if (ctx->error) goto ga_exit;
(void)t2;
(void)gravity_aot_field_set(ctx,v0,2,t2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1 = t2;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static gravity_aot_value ada_native_fixture_fn_20(gravity_aot_context *ctx, gravity_aot_value receiver, const gravity_aot_value *args, uint32_t argc) {
gravity_aot_value result=gravity_aot_null(); if (!ctx) return result;
if (ctx->abi_version!=GRAVITY_AOT_ABI_VERSION) { gravity_aot_error(ctx,GRAVITY_AOT_BAD_ABI); return result; }
if (argc!=1 || (argc && !args)) { gravity_aot_error(ctx,GRAVITY_AOT_ARITY); return result; }
if (ctx->depth>=ctx->max_depth || !gravity_aot_tick(ctx)) { gravity_aot_error(ctx,GRAVITY_AOT_LIMIT); return result; }
++ctx->depth;
gravity_aot_value v0=receiver; (void)v0;
if (receiver.kind!=GRAVITY_AOT_OBJECT || !receiver.object || receiver.object->type!=&ga_ada_native_fixture_types[4]) { gravity_aot_error(ctx,GRAVITY_AOT_TYPE); goto ga_exit; }
gravity_aot_value v1=gravity_aot_copy(ctx,args[0]); (void)v1;
if (ctx->error) goto ga_exit;
{
gravity_aot_value t2 = gravity_aot_int((int64_t)UINT64_C(0));
(void)t2;
(void)gravity_aot_field_set(ctx,v0,2,t2);
if (ctx->error) goto ga_exit;
gravity_aot_value t1 = t2;
(void)t1;
}
goto ga_exit;
ga_exit:
--ctx->depth;
return ctx->error?gravity_aot_null():result;
}
static const gravity_aot_attribute_value ga_attr_value_1 = {.kind=1,.count=0,.text="\141\157\164\056\151\156\164\145\147\162\141\164\151\157\156\056\160\157\163\151\164\151\157\156"};
static const gravity_aot_attribute_argument ga_args_0_0[] = {
{"\151\144",&ga_attr_value_1},
};
static const gravity_aot_attribute ga_attrs_0[] = {
{"\143\157\155\160\157\156\145\156\164",1,0,1,0,ga_args_0_0},
};
static const gravity_aot_attribute ga_attrs_1[] = {
{"\145\170\160\157\162\164",0,0,2,23,NULL},
};
static const gravity_aot_attribute_value ga_attr_value_2 = {.kind=1,.count=0,.text="\141\157\164\056\151\156\164\145\147\162\141\164\151\157\156\056\164\151\155\145"};
static const gravity_aot_attribute_value ga_attr_value_3 = {.kind=4,.count=0,.integer=1};
static const gravity_aot_attribute_argument ga_args_2_0[] = {
{"\151\144",&ga_attr_value_2},
{"\141\165\164\157\111\156\163\145\162\164",&ga_attr_value_3},
};
static const gravity_aot_attribute ga_attrs_2[] = {
{"\162\145\163\157\165\162\143\145",2,0,3,1,ga_args_2_0},
};
static const gravity_aot_attribute ga_attrs_3[] = {
{"\145\170\160\157\162\164",0,0,4,19,NULL},
};
static const gravity_aot_attribute_value ga_attr_value_4 = {.kind=1,.count=0,.text="\156\141\164\151\166\145\056\163\143\141\154\145"};
static const gravity_aot_attribute_value ga_attr_value_5 = {.kind=1,.count=0,.text="\165\160\144\141\164\145"};
static const gravity_aot_attribute_argument ga_args_4_0[] = {
{"\151\144",&ga_attr_value_4},
{"\163\143\150\145\144\165\154\145\162",&ga_attr_value_5},
};
static const gravity_aot_attribute ga_attrs_4[] = {
{"\163\171\163\164\145\155",2,0,5,1,ga_args_4_0},
};
static const gravity_aot_attribute_value ga_attr_value_6 = {.kind=0,.count=0,.text="\124\151\155\145\104\141\164\141"};
static const gravity_aot_attribute_argument ga_args_5_0[] = {
{NULL,&ga_attr_value_6},
};
static const gravity_aot_attribute ga_attrs_5[] = {
{"\162\145\163\157\165\162\143\145",1,0,7,5,ga_args_5_0},
};
static const gravity_aot_parameter ga_params_6[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_attribute_value ga_attr_value_7 = {.kind=1,.count=0,.text="\156\141\164\151\166\145\056\155\157\166\145\155\145\156\164"};
static const gravity_aot_attribute_value ga_attr_value_8 = {.kind=1,.count=0,.text="\165\160\144\141\164\145"};
static const gravity_aot_attribute_argument ga_args_7_0[] = {
{"\151\144",&ga_attr_value_7},
{"\163\143\150\145\144\165\154\145\162",&ga_attr_value_8},
};
static const gravity_aot_attribute_value ga_attr_value_9 = {.kind=1,.count=0,.text="\156\141\164\151\166\145\056\163\143\141\154\145"};
static const gravity_aot_attribute_argument ga_args_7_1[] = {
{"\151\144",&ga_attr_value_9},
};
static const gravity_aot_attribute ga_attrs_7[] = {
{"\163\171\163\164\145\155",2,0,10,1,ga_args_7_0},
{"\141\146\164\145\162",1,0,11,1,ga_args_7_1},
};
static const gravity_aot_attribute_value ga_attr_value_10 = {.kind=0,.count=0,.text="\120\157\163\151\164\151\157\156\104\141\164\141"};
static const gravity_aot_attribute_value ga_attr_value_11 = {.kind=0,.count=0,.text="\116\141\164\151\166\145\126\145\154\157\143\151\164\171"};
static const gravity_aot_attribute_value ga_attr_value_12 = {.kind=0,.count=0,.text="\116\141\164\151\166\145\115\157\166\141\142\154\145"};
static const gravity_aot_attribute_value ga_attr_value_13 = {.kind=0,.count=0,.text="\116\141\164\151\166\145\106\162\157\172\145\156"};
static const gravity_aot_attribute_argument ga_args_8_0[] = {
{NULL,&ga_attr_value_10},
{NULL,&ga_attr_value_11},
{"\167\151\164\150",&ga_attr_value_12},
{"\167\151\164\150\157\165\164",&ga_attr_value_13},
};
static const gravity_aot_attribute ga_attrs_8[] = {
{"\161\165\145\162\171",4,0,13,5,ga_args_8_0},
};
static const gravity_aot_attribute_value ga_attr_value_14 = {.kind=0,.count=0,.text="\124\151\155\145\104\141\164\141"};
static const gravity_aot_attribute_argument ga_args_9_0[] = {
{NULL,&ga_attr_value_14},
};
static const gravity_aot_attribute ga_attrs_9[] = {
{"\162\145\163\157\165\162\143\145",1,0,14,5,ga_args_9_0},
};
static const gravity_aot_parameter ga_params_11[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_attribute_value ga_attr_value_15 = {.kind=1,.count=0,.text="\141\157\164\056\151\156\164\145\147\162\141\164\151\157\156\056\143\157\156\164\162\157\154\154\145\162"};
static const gravity_aot_attribute_value ga_attr_value_16 = {.kind=2,.count=0,.integer=(int64_t)UINT64_C(1)};
static const gravity_aot_attribute_value ga_attr_value_18 = {.kind=1,.count=0,.text="\116\141\164\151\166\145\103\157\156\164\162\157\154\154\145\162"};
static const gravity_aot_attribute_value *const ga_attr_items_17[] = {&ga_attr_value_18,};
static const gravity_aot_attribute_value ga_attr_value_17 = {.kind=6,.count=1,.items=ga_attr_items_17};
static const gravity_aot_attribute_argument ga_args_12_0[] = {
{"\151\144",&ga_attr_value_15},
{"\166\145\162\163\151\157\156",&ga_attr_value_16},
{"\141\154\151\141\163\145\163",&ga_attr_value_17},
};
static const gravity_aot_attribute ga_attrs_12[] = {
{"\163\143\162\151\160\164\141\142\154\145",3,0,23,1,ga_args_12_0},
};
static const gravity_aot_attribute_value ga_attr_value_19 = {.kind=0,.count=0,.text="\120\157\163\151\164\151\157\156\104\141\164\141"};
static const gravity_aot_attribute_value ga_attr_value_20 = {.kind=4,.count=0,.integer=1};
static const gravity_aot_attribute_argument ga_args_13_0[] = {
{NULL,&ga_attr_value_19},
{"\162\145\161\165\151\162\145\144",&ga_attr_value_20},
};
static const gravity_aot_attribute ga_attrs_13[] = {
{"\143\157\155\160\157\156\145\156\164",2,0,25,5,ga_args_13_0},
};
static const gravity_aot_attribute_value ga_attr_value_21 = {.kind=0,.count=0,.text="\124\151\155\145\104\141\164\141"};
static const gravity_aot_attribute_argument ga_args_14_0[] = {
{NULL,&ga_attr_value_21},
};
static const gravity_aot_attribute ga_attrs_14[] = {
{"\162\145\163\157\165\162\143\145",1,0,26,5,ga_args_14_0},
};
static const gravity_aot_attribute ga_attrs_15[] = {
{"\145\170\160\157\162\164",0,0,27,5,NULL},
};
static const gravity_aot_parameter ga_params_16[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_17[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_18[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_19[] = {
{"\145\166\145\156\164\163",NULL},
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_parameter ga_params_20[] = {
{"\143\157\156\164\145\170\164",NULL},
};
static const gravity_aot_declaration ga_ada_native_fixture_declarations[] = {
{"\120\157\163\151\164\151\157\156\104\141\164\141",NULL,NULL,2,0,2,1,1,ga_attrs_0,0,NULL},
{"\166\141\154\165\145","\120\157\163\151\164\151\157\156\104\141\164\141",NULL,3,0,2,35,1,ga_attrs_1,0,NULL},
{"\124\151\155\145\104\141\164\141",NULL,NULL,2,0,4,1,1,ga_attrs_2,0,NULL},
{"\146\141\143\164\157\162","\124\151\155\145\104\141\164\141",NULL,3,0,4,31,1,ga_attrs_3,0,NULL},
{"\123\143\141\154\145\123\171\163\164\145\155",NULL,NULL,1,0,6,1,1,ga_attrs_4,0,NULL},
{"\164\151\155\145","\123\143\141\154\145\123\171\163\164\145\155",NULL,3,0,7,29,1,ga_attrs_5,0,NULL},
{"\165\160\144\141\164\145","\123\143\141\154\145\123\171\163\164\145\155",NULL,4,0,8,5,0,NULL,1,ga_params_6},
{"\115\157\166\145\155\145\156\164\123\171\163\164\145\155",NULL,NULL,1,0,12,1,2,ga_attrs_7,0,NULL},
{"\162\157\167\163","\115\157\166\145\155\145\156\164\123\171\163\164\145\155",NULL,3,0,13,90,1,ga_attrs_8,0,NULL},
{"\164\151\155\145","\115\157\166\145\155\145\156\164\123\171\163\164\145\155",NULL,3,0,14,29,1,ga_attrs_9,0,NULL},
{"\165\160\144\141\164\145\163","\115\157\166\145\155\145\156\164\123\171\163\164\145\155",NULL,3,0,15,9,0,NULL,0,NULL},
{"\165\160\144\141\164\145","\115\157\166\145\155\145\156\164\123\171\163\164\145\155",NULL,4,0,16,5,0,NULL,1,ga_params_11},
{"\103\157\156\164\162\157\154\154\145\162",NULL,NULL,1,0,24,1,1,ga_attrs_12,0,NULL},
{"\160\157\163\151\164\151\157\156","\103\157\156\164\162\157\154\154\145\162",NULL,3,0,25,50,1,ga_attrs_13,0,NULL},
{"\164\151\155\145","\103\157\156\164\162\157\154\154\145\162",NULL,3,0,26,29,1,ga_attrs_14,0,NULL},
{"\150\145\141\154\164\150","\103\157\156\164\162\157\154\154\145\162",NULL,3,0,27,17,1,ga_attrs_15,0,NULL},
{"\162\145\141\144\171","\103\157\156\164\162\157\154\154\145\162",NULL,4,0,28,5,0,NULL,1,ga_params_16},
{"\165\160\144\141\164\145","\103\157\156\164\162\157\154\154\145\162",NULL,4,0,29,5,0,NULL,1,ga_params_17},
{"\146\151\170\145\144\125\160\144\141\164\145","\103\157\156\164\162\157\154\154\145\162",NULL,4,0,30,5,0,NULL,1,ga_params_18},
{"\145\166\145\156\164","\103\157\156\164\162\157\154\154\145\162",NULL,4,0,31,5,0,NULL,2,ga_params_19},
{"\144\145\163\164\162\157\171","\103\157\156\164\162\157\154\154\145\162",NULL,4,0,32,5,0,NULL,1,ga_params_20},
};
static const gravity_aot_field ga_fields_0[] = {
{&ga_ada_native_fixture_declarations[1],{.floating=0x0p+0,.kind=GRAVITY_AOT_FLOAT},0,NULL},
};
static const gravity_aot_field ga_fields_1[] = {
{&ga_ada_native_fixture_declarations[3],{.floating=0x1p+1,.kind=GRAVITY_AOT_FLOAT},0,NULL},
};
static const gravity_aot_field ga_fields_2[] = {
{&ga_ada_native_fixture_declarations[5],{0},0,NULL},
};
static const gravity_aot_method_export ga_methods_2[] = {
{"\165\160\144\141\164\145",1,ada_native_fixture_fn_6,&ga_ada_native_fixture_declarations[6]},
};
static const gravity_aot_field ga_fields_3[] = {
{&ga_ada_native_fixture_declarations[8],{0},0,NULL},
{&ga_ada_native_fixture_declarations[9],{0},0,NULL},
{&ga_ada_native_fixture_declarations[10],{.integer=(int64_t)UINT64_C(0),.kind=1},0,NULL},
};
static const gravity_aot_method_export ga_methods_3[] = {
{"\165\160\144\141\164\145",1,ada_native_fixture_fn_11,&ga_ada_native_fixture_declarations[11]},
};
static const gravity_aot_field ga_fields_4[] = {
{&ga_ada_native_fixture_declarations[13],{0},0,NULL},
{&ga_ada_native_fixture_declarations[14],{0},0,NULL},
{&ga_ada_native_fixture_declarations[15],{.integer=(int64_t)UINT64_C(10),.kind=1},0,NULL},
};
static const gravity_aot_method_export ga_methods_4[] = {
{"\162\145\141\144\171",1,ada_native_fixture_fn_16,&ga_ada_native_fixture_declarations[16]},
{"\165\160\144\141\164\145",1,ada_native_fixture_fn_17,&ga_ada_native_fixture_declarations[17]},
{"\146\151\170\145\144\125\160\144\141\164\145",1,ada_native_fixture_fn_18,&ga_ada_native_fixture_declarations[18]},
{"\145\166\145\156\164",2,ada_native_fixture_fn_19,&ga_ada_native_fixture_declarations[19]},
{"\144\145\163\164\162\157\171",1,ada_native_fixture_fn_20,&ga_ada_native_fixture_declarations[20]},
};
static const gravity_aot_class ga_ada_native_fixture_types[5] = {
{&ga_ada_native_fixture_declarations[0],1,1,0,ga_fields_0,NULL},
{&ga_ada_native_fixture_declarations[2],1,1,0,ga_fields_1,NULL},
{&ga_ada_native_fixture_declarations[4],0,1,1,ga_fields_2,ga_methods_2},
{&ga_ada_native_fixture_declarations[7],0,3,1,ga_fields_3,ga_methods_3},
{&ga_ada_native_fixture_declarations[12],0,3,5,ga_fields_4,ga_methods_4},
};
const gravity_aot_module *ada_native_fixture_get_module(void) {
static const gravity_aot_module m={GRAVITY_AOT_ABI_VERSION,0,NULL,5,21,ga_ada_native_fixture_types,ga_ada_native_fixture_declarations};
return &m;
}
