/// One named input accepted by a generated runtime component constructor.
public struct RuntimeComponentConstructorParameter: Equatable, Sendable {
    public let kind: ReflectedFieldKind
    public let name: String

    public init(name: String, kind: ReflectedFieldKind) {
        self.kind = kind
        self.name = name
    }
}

/// Errors produced while materializing a component from detached runtime values.
public enum RuntimeComponentConstructorError: Error, Equatable, Sendable {
    case argumentCount(expected: Int, actual: Int)
    case invalidArgument(component: String, parameter: String)
    case invalidBase(component: String)
    case missingArgument(component: String, parameter: String)
    case missingDefaultFactory(component: String)
}

/// Type-owned constructor metadata generated by ``Component()``.
///
/// The generated apply closure writes supported stored properties directly on
/// the concrete component value. It performs no string lookup or reflection
/// traversal on the construction path.
public struct RuntimeComponentConstructorDescriptor: @unchecked Sendable {
    public let parameters: [RuntimeComponentConstructorParameter]
    public let typeName: String

    /// Whether construction needs an alias-specific default component.
    public var requiresDefaultComponent: Bool {
        constructArguments == nil
    }

    private let applyArguments: (@Sendable (
        consuming any Component,
        [ReflectedFieldValue?]
    ) throws -> any Component)?
    private let constructArguments: (@Sendable (
        [ReflectedFieldValue?]
    ) throws -> any Component)?

    public init(
        typeName: String,
        parameters: [RuntimeComponentConstructorParameter],
        applyArguments: @escaping @Sendable (
            consuming any Component,
            [ReflectedFieldValue?]
        ) throws -> any Component
    ) {
        self.applyArguments = applyArguments
        self.constructArguments = nil
        self.parameters = parameters
        self.typeName = typeName
    }

    /// Creates a descriptor backed by a real Swift initializer.
    ///
    /// Unlike the fieldwise bridge, this form does not materialize a default
    /// component before construction and therefore preserves initializer
    /// invariants without adding work to the spawn path.
    public init(
        typeName: String,
        parameters: [RuntimeComponentConstructorParameter],
        constructArguments: @escaping @Sendable (
            [ReflectedFieldValue?]
        ) throws -> any Component
    ) {
        self.applyArguments = nil
        self.constructArguments = constructArguments
        self.parameters = parameters
        self.typeName = typeName
    }

    package func apply(
        to component: consuming any Component,
        arguments: [ReflectedFieldValue?]
    ) throws -> any Component {
        guard arguments.count == parameters.count else {
            throw RuntimeComponentConstructorError.argumentCount(
                expected: parameters.count,
                actual: arguments.count
            )
        }
        if let constructArguments {
            return try constructArguments(arguments)
        }
        guard let applyArguments else {
            preconditionFailure("Runtime component constructor has no implementation")
        }
        return try applyArguments(component, arguments)
    }

    package func construct(
        arguments: [ReflectedFieldValue?],
        makeDefault: (@Sendable () -> any Component)?
    ) throws -> any Component {
        guard arguments.count == parameters.count else {
            throw RuntimeComponentConstructorError.argumentCount(
                expected: parameters.count,
                actual: arguments.count
            )
        }
        if let constructArguments {
            return try constructArguments(arguments)
        }
        guard let makeDefault else {
            throw RuntimeComponentConstructorError.missingDefaultFactory(component: typeName)
        }
        guard let applyArguments else {
            preconditionFailure("Runtime component constructor has no implementation")
        }
        return try applyArguments(makeDefault(), arguments)
    }
}

/// A component whose runtime constructor metadata was generated by
/// ``Component()``. A fieldwise constructor needs an alias-specific default
/// factory; an ``AdaScriptInit()`` constructor can be registered directly.
public protocol RuntimeConstructibleComponent: Component {
    static var runtimeComponentConstructor: RuntimeComponentConstructorDescriptor { get }
}

/// A registered alias resolved once while an AdaScript module is linked.
public struct RegisteredRuntimeComponentConstructor: @unchecked Sendable {
    public let name: String
    public let parameters: [RuntimeComponentConstructorParameter]
    public let typeName: String

    private let constructValue: @Sendable ([ReflectedFieldValue?]) throws -> any Component

    package init(
        name: String,
        descriptor: RuntimeComponentConstructorDescriptor,
        makeDefault: (@Sendable () -> any Component)?
    ) {
        self.name = name
        self.parameters = descriptor.parameters
        self.typeName = descriptor.typeName
        self.constructValue = { arguments in
            try descriptor.construct(arguments: arguments, makeDefault: makeDefault)
        }
    }

    public func construct(arguments: [ReflectedFieldValue?]) throws -> any Component {
        try constructValue(arguments)
    }
}
